import React from "react";
import {
  View,
  Text,
  Dimensions,
  StyleSheet,
  TouchableOpacity,
  item
} from "react-native";
import {
  LineChart,
  BarChart,
  PieChart,
  ProgressChart,
  ContributionGraph,
} from "react-native-chart-kit";

const ht = Dimensions.get("window").height;
const wd = Dimensions.get("window").width;

function Stats() {
 const arr = [
   {
     year: "2017",
     date: "5-april-2017",
     team_1: "Mumbai Indians",
     team_2: " Chennai Super Kings",
     Venue: "hyderabad",
     wonBy: "Mumbai Indians",
   },
   {
     year: "2017",
     date: "6-april-2017",
     team_1: "Gujarat Lions  ",
     team_2: "Kolkata Knight Riders",
     Venue: "Saurashtra Cricket Association Stadium, Rajkot",
     wonBy: "Gujarat Lions ",
   },
   {
     year: "2017",
     date: "6-april-2017",
     team_1: "Rising Pune Supergiants ",
     team_2: "Mumbai Indians",
     Venue: "Maharashtra Cricket Association's International Stadium, Pune",
     wonBy: "Mumbai Indians ",
   },
   {
     year: "2017",
     date: "8-april-2017",
     team_1: "Kings XI Punjab ",
     team_2: "Mumbai Indians",
     Venue: "Maharashtra Cricket Association's International Stadium, Pune",
     wonBy: "Mumbai Indians ",
   },
   {
     year: "2017",
     date: "8-april-2017",
     team_1: "Royal Challengers Bangalore ",
     team_2: " Delhi Daredevils",
     Venue: "M. Chinnaswamy Stadium, Bengaluru",
     wonBy: "Royal Challengers Bangalore ",
   },
   {
     year: "2017",
     date: "8-april-2017",
     team_1: "Sunrisers Hyderabad",
     team_2: " Gujarat Lions",
     Venue: "Rajiv Gandhi Intl. Cricket Stadium, Hyderabad",
     wonBy: "Gujarat Lions ",
   },
   {
     year: "2017",
     date: "9-april-2017",
     team_1: "Mumbai Indians",
     team_2: "Kolkata Knight Riders",
     Venue: "Wankhede Stadium, Mumbai",
     wonBy: "Kolkata Knight Riders ",
   },
   {
     year: "2017",
     date: "10-april-2017",
     team_1: "Kings XI Punjab",
     team_2: "Royal Challengers Bangalore",
     Venue: "Holkar Cricket Stadium, Indore",
     wonBy: "Kings XI Punjab",
   },
   {
     year: "2017",
     date: "11-april-2017",
     team_1: "Rising Pune Supergiants",
     team_2: "Delhi Daredevils",
     Venue: "Maharashtra Cricket Association's International Stadium, Pune",
     wonBy: "Delhi Daredevils",
   },
   {
     year: "2017",
     date: "12-april-2017",
     team_1: "Mumbai Indians",
     team_2: "Sunrisers Hyderabad",
     Venue: "Wankhede Stadium, Mumbai",
     wonBy: "Sunrisers Hyderabad",
   },
   {
     year: "2017",
     date: "12-april-2017",
     team_1: "Mumbai Indians",
     team_2: "Kolkata Knight Riders",
     Venue: "Holkar Cricket Stadium, Indore",
     wonBy: "Mumbai IndiansS",
   },
   {
     year: "2017",
     date: "13-april-2017",
     team_1: "Gujarat Lions",
     team_2: "Delhi Daredevils",
     Venue: "Wankhede Stadium, Mumbai",
     wonBy: "Delhi Daredevils",
   },
   {
     year: "2017",
     date: "14-april-2017",
     team_1: "Rising Pune Supergiants",
     team_2: "Delhi Daredevils",
     Venue: "Eden Gardens, Kolkata",
     wonBy: "Rising Pune Supergiants",
   },
   {
     year: "2017",
     date: "14-april-2017",
     team_1: "Gujarat Lions",
     team_2: "Delhi Daredevils",
     Venue: "Eden Gardens, Kolkata",
     wonBy: "Delhi Daredevils",
   },
   {
     year: "2017",
     date: "15-april-2017",
     team_1: "Kolkata Knight Riders",
     team_2: "Sunrisers Hyderabad",
     Venue: "Rajiv Gandhi Intl. Cricket Stadium, Hyderabad",
     wonBy: "Sunrisers Hyderabad",
   },
   {
     year: "2017",
     date: "16-april-2017",
     team_1: "Mumbai Indians",
     team_2: "Gujarat Lions",
     Venue: "M. Chinnaswamy Stadium, Bengaluru",
     wonBy: "Gujarat Lions",
   },
   {
     year: "2017",
     date: "17-april-2017",
     team_1: "Delhi Daredevils",
     team_2: "Kings XI Punjab",
     Venue: "Rajiv Gandhi Intl. Cricket Stadium, Hyderabad",
     wonBy: "Kings XI Punjab",
   },
   {
     year: "2017",
     date: "18-april-2017",
     team_1: "Gujarat Lions",
     team_2: "Royal Challengers Bangalore",
     Venue: "Saurashtra Cricket Association Stadium, Rajkot",
     wonBy: "Gujarat Lions",
   },
   {
     year: "2017",
     date: "19-april-2017",
     team_1: "Sunrisers Hyderabad",
     team_2: "Delhi Daredevils",
     Venue: "Rajiv Gandhi Intl. Cricket Stadium, Hyderabad",
     wonBy: "Delhi Daredevils",
   },
   {
     year: "2017",
     date: "20-april-2017",
     team_1: "Kings XI Punjab",
     team_2: "Mumbai Indians",
     Venue: "Holkar Cricket Stadium, Indore",
     wonBy: "Delhi Daredevils",
   },
   {
     year: "2017",
     date: "21-april-2017",
     team_1: "Kolkata Knight Riders",
     team_2: "Gujarat Lions",
     Venue: "Eden Gardens, Kolkata",
     wonBy: "Gujarat Lions",
   },
   {
     year: "2017",
     date: "22-april-2017",
     team_1: "Delhi Daredevils",
     team_2: "Mumbai Indians",
     Venue: "Feroz Shah Kotla Ground, Delhi i",
     wonBy: "Delhi Daredevils",
   },
   {
     year: "2017",
     date: "22-april-2017",
     team_1: "Rising Pune Supergiants",
     team_2: "Sunrisers Hyderabad",
     Venue: "Maharashtra Cricket Association's International Stadium, Pune",
     wonBy: "Rising Pune Supergiants",
   },
   {
     year: "2017",
     date: "23-april-2017",
     team_1: "Kings XI Punjab",
     team_2: "Gujarat Lions",
     Venue: "Saurashtra Cricket Association Stadium, Rajkot",
     wonBy: "Gujarat Lions",
   },
   {
     year: "2017",
     date: "23-april-2017",
     team_1: "Kolkata Knight Riders",
     team_2: "Royal Challengers Bangalore",
     Venue: "Eden Gardens, Kolkata",
     wonBy: "Royal Challengers Bangalore",
   },
   {
     year: "2017",
     date: "24-april-2017",
     team_1: "Mumbai Indians",
     team_2: "Rising Pune Supergiants",
     Venue: "Wankhede Stadium, Mumbai",
     wonBy: "Rising Pune Supergiants",
   },
   {
     year: "2017",
     date: "25-april-2017",
     team_1: "Royal Challengers Bangalore",
     team_2: "Sunrisers Hyderabad",
     Venue: "Wankhede Stadium, Mumbai",
     wonBy: "Sunrisers Hyderabad",
   },
   {
     year: "2017",
     date: "26-april-2017",
     team_1: "Rising Pune Supergiants",
     team_2: "Kolkata Knight Riders",
     Venue: "Maharashtra Cricket Association's International Stadium, Pune",
     wonBy: "Kolkata Knight Riders",
   },
   {
     year: "2017",
     date: "27-april-2017",
     team_1: "Rising Pune Supergiants",
     team_2: "Kolkata Knight Riders",
     Venue: "Maharashtra Cricket Association's International Stadium, Pune",
     wonBy: "Kolkata Knight Riders",
   },
   {
     year: "2017",
     date: "28-april-2017",
     team_1: "Mumbai Indians",
     team_2: "Delhi Daredevils",
     Venue: "Maharashtra Cricket Association's International Stadium, Pune",
     wonBy: "Delhi Daredevils",
   },
   {
     year: "2017",
     date: "28-april-2017",
     team_1: "Mumbai Indians",
     team_2: "Delhi Daredevils",
     Venue: "Maharashtra Cricket Association's International Stadium, Pune",
     wonBy: "Delhi Daredevils",
   },
   {
     year: "2018",
     date: "5-april-2018",
     team_1: "Mumbai Indians",
     team_2: " Chennai Super Kings",
     Venue: "hyderabad",
     wonBy: "Mumbai Indians",
   },
   {
     year: "2018",
     date: "6-april-2018",
     team_1: "Chennai Super Kings  ",
     team_2: "Kolkata Knight Riders",
     Venue: "Saurashtra Cricket Association Stadium, Rajkot",
     wonBy: "Chennai Super Kings ",
   },
   {
     year: "2018",
     date: "6-april-2018",
     team_1: "Kolkata Knight Riders ",
     team_2: "Mumbai Indians",
     Venue: "Maharashtra Cricket Association's International Stadium, Pune",
     wonBy: "Mumbai Indians ",
   },
   {
     year: "2018",
     date: "8-april-2018",
     team_1: "Kolkata Knight Riders",
     team_2: "Mumbai Indians",
     Venue: "Maharashtra Cricket Association's International Stadium, Pune",
     wonBy: "Kolkata Knight Riders ",
   },
   {
     year: "2018",
     date: "8-april-2018",
     team_1: "Royal Challengers Bangalore ",
     team_2: " Delhi Daredevils",
     Venue: "M. Chinnaswamy Stadium, Bengaluru",
     wonBy: "Royal Challengers Bangalore ",
   },
   {
     year: "2018",
     date: "8-april-2018",
     team_1: "Sunrisers Hyderabad",
     team_2: " Delhi Daredevils",
     Venue: "Rajiv Gandhi Intl. Cricket Stadium, Hyderabad",
     wonBy: "Gujarat Lions ",
   },
   {
     year: "2018",
     date: "9-april-2018",
     team_1: "Royal Challengers Bangalore",
     team_2: "Kolkata Knight Riders",
     Venue: "Wankhede Stadium, Mumbai",
     wonBy: "Royal Challengers Bangalore",
   },
   {
     year: "2018",
     date: "10-april-2018",
     team_1: "Kings XI Punjab",
     team_2: "Royal Challengers Bangalore",
     Venue: "Holkar Cricket Stadium, Indore",
     wonBy: "Kings XI Punjab",
   },
   {
     year: "2018",
     date: "11-april-2018",
     team_1: "Rising Pune Supergiants",
     team_2: "Royal Challengers Bangalore",
     Venue: "Holkar Cricket Stadium, Indore",
     wonBy: "Rising Pune Supergiants",
   },
   {
     year: "2018",
     date: "12-april-2018",
     team_1: "Mumbai Indians",
     team_2: "Sunrisers Hyderabad",
     Venue: "Wankhede Stadium, Mumbai",
     wonBy: "Rising Pune Supergiants",
   },
   {
     year: "2018",
     date: "12-april-2018",
     team_1: "Mumbai Indians",
     team_2: "Kolkata Knight Riders",
     Venue: "Holkar Cricket Stadium, Indore",
     wonBy: "Mumbai IndiansS",
   },
   {
     year: "2018",
     date: "13-april-2018",
     team_1: "Gujarat Lions",
     team_2: "Delhi Daredevils",
     Venue: "Wankhede Stadium, Mumbai",
     wonBy: "Delhi Daredevils",
   },
   {
     year: "2018",
     date: "14-april-2018",
     team_1: "Rising Pune Supergiants",
     team_2: "Delhi Daredevils",
     Venue: "Eden Gardens, Kolkata",
     wonBy: "Rising Pune Supergiants",
   },
   {
     year: "2018",
     date: "14-april-2018",
     team_1: "Gujarat Lions",
     team_2: "Delhi Daredevils",
     Venue: "Eden Gardens, Kolkata",
     wonBy: "Delhi Daredevils",
   },
   {
     year: "2018",
     date: "15-april-2018",
     team_1: "Gujarat Lions",
     team_2: "Sunrisers Hyderabad",
     Venue: "Rajiv Gandhi Intl. Cricket Stadium, Hyderabad",
     wonBy: "Sunrisers Hyderabad",
   },
   {
     year: "2018",
     date: "16-april-2018",
     team_1: "Mumbai Indians",
     team_2: "Gujarat Lions",
     Venue: "M. Chinnaswamy Stadium, Bengaluru",
     wonBy: "Gujarat Lions",
   },
   {
     year: "2018",
     date: "17-april-2018",
     team_1: "Delhi Daredevils",
     team_2: "Kings XI Punjab",
     Venue: "Rajiv Gandhi Intl. Cricket Stadium, Hyderabad",
     wonBy: "Kings XI Punjab",
   },
   {
     year: "2018",
     date: "18-april-2018",
     team_1: "Gujarat Lions",
     team_2: "Mumbai Indians",
     Venue: "Saurashtra Cricket Association Stadium, Rajkot",
     wonBy: "Gujarat Lions",
   },
   {
     year: "2018",
     date: "19-april-2018",
     team_1: "Sunrisers Hyderabad",
     team_2: "Delhi Daredevils",
     Venue: "Rajiv Gandhi Intl. Cricket Stadium, Hyderabad",
     wonBy: "Delhi Daredevils",
   },
   {
     year: "2018",
     date: "20-april-2018",
     team_1: "Kings XI Punjab",
     team_2: "Sunrisers Hyderabad",
     Venue: "Holkar Cricket Stadium, Indore",
     wonBy: "Sunrisers Hyderabad",
   },
   {
     year: "2018",
     date: "21-april-2018",
     team_1: "Kolkata Knight Riders",
     team_2: "Gujarat Lions",
     Venue: "Eden Gardens, Kolkata",
     wonBy: "Gujarat Lions",
   },
   {
     year: "2018",
     date: "22-april-2018",
     team_1: "Delhi Daredevils",
     team_2: "Mumbai Indians",
     Venue: "Feroz Shah Kotla Ground, Delhi i",
     wonBy: "Delhi Daredevils",
   },
   {
     year: "2018",
     date: "22-april-2018",
     team_1: "Rising Pune Supergiants",
     team_2: "Sunrisers Hyderabad",
     Venue: "Maharashtra Cricket Association's International Stadium, Pune",
     wonBy: "Rising Pune Supergiants",
   },
   {
     year: "2018",
     date: "23-april-2018",
     team_1: "Kings XI Punjab",
     team_2: "Gujarat Lions",
     Venue: "Saurashtra Cricket Association Stadium, Rajkot",
     wonBy: "Gujarat Lions",
   },
   {
     year: "2018",
     date: "23-april-2018",
     team_1: "Kolkata Knight Riders",
     team_2: "Royal Challengers Bangalore",
     Venue: "Eden Gardens, Kolkata",
     wonBy: "Royal Challengers Bangalore",
   },
   {
     year: "2018",
     date: "24-april-2018",
     team_1: "Mumbai Indians",
     team_2: "Rising Pune Supergiants",
     Venue: "Wankhede Stadium, Mumbai",
     wonBy: "Rising Pune Supergiants",
   },
   {
     year: "2018",
     date: "25-april-2018",
     team_1: "Royal Challengers Bangalore",
     team_2: "Sunrisers Hyderabad",
     Venue: "Wankhede Stadium, Mumbai",
     wonBy: "Sunrisers Hyderabad",
   },
   {
     year: "2018",
     date: "26-april-2018",
     team_1: "Rising Pune Supergiants",
     team_2: "Kolkata Knight Riders",
     Venue: "Maharashtra Cricket Association's International Stadium, Pune",
     wonBy: "Kolkata Knight Riders",
   },
   {
     year: "2018",
     date: "27-april-2018",
     team_1: "Rising Pune Supergiants",
     team_2: "Mumbai Indians",
     Venue: "Maharashtra Cricket Association's International Stadium, Pune",
     wonBy: "Mumbai Indians",
   },
   {
     year: "2018",
     date: "28-april-2018",
     team_1: "Sunrisers Hyderabad",
     team_2: "Delhi Daredevils",
     Venue: "Maharashtra Cricket Association's International Stadium, Pune",
     wonBy: "Delhi Daredevils",
   },
   {
     year: "2018",
     date: "28-april-2018",
     team_1: "Mumbai Indians",
     team_2: "Delhi Daredevils",
     Venue: "Maharashtra Cricket Association's International Stadium, Pune",
     wonBy: "Delhi Daredevils",
   },
   {
     year: "2019",
     date: "5-may-2019",
     team_1: "Kolkata Knight Riders",
     team_2: " Chennai Super Kings",
     Venue: "hyderabad",
     wonBy: "Mumbai Indians",
   },
   {
     year: "2019",
     date: "6-may-2019",
     team_1: "Chennai Super Kings  ",
     team_2: "Kolkata Knight Riders",
     Venue: "Saurashtra Cricket Association Stadium, Rajkot",
     wonBy: "Chennai Super Kings ",
   },
   {
     year: "2019",
     date: "6-may-2019",
     team_1: "Kolkata Knight Riders ",
     team_2: "Mumbai Indians",
     Venue: "Maharashtra Cricket Association's International Stadium, Pune",
     wonBy: "Mumbai Indians ",
   },
   {
     year: "2019",
     date: "8-may-2019",
     team_1: "Kolkata Knight Riders",
     team_2: "Delhi Daredevils",
     Venue: "Maharashtra Cricket Association's International Stadium, Pune",
     wonBy: "Kolkata Knight Riders ",
   },
   {
     year: "2019",
     date: "8-may-2019",
     team_1: "Royal Challengers Bangalore ",
     team_2: " Delhi Daredevils",
     Venue: "M. Chinnaswamy Stadium, Bengaluru",
     wonBy: "Royal Challengers Bangalore ",
   },
   {
     year: "2019",
     date: "8-may-2019",
     team_1: "Sunrisers Hyderabad",
     team_2: " Delhi Daredevils",
     Venue: "Rajiv Gandhi Intl. Cricket Stadium, Hyderabad",
     wonBy: "Gujarat Lions ",
   },
   {
     year: "2019",
     date: "9-may-2019",
     team_1: "Royal Challengers Bangalore",
     team_2: "Kolkata Knight Riders",
     Venue: "Wankhede Stadium, Mumbai",
     wonBy: "Royal Challengers Bangalore",
   },
   {
     year: "2019",
     date: "10-may-2019",
     team_1: "Kings XI Punjab",
     team_2: "Royal Challengers Bangalore",
     Venue: "Holkar Cricket Stadium, Indore",
     wonBy: "Kings XI Punjab",
   },
   {
     year: "2019",
     date: "11-may-2019",
     team_1: "Rising Pune Supergiants",
     team_2: "Royal Challengers Bangalore",
     Venue: "Holkar Cricket Stadium, Indore",
     wonBy: "ising Pune Supergiants",
   },
   {
     year: "2019",
     date: "12-may-2019",
     team_1: "Mumbai Indians",
     team_2: "Sunrisers Hyderabad",
     Venue: "Wankhede Stadium, Mumbai",
     wonBy: "ising Pune Supergiants",
   },
   {
     year: "2019",
     date: "12-may-2019",
     team_1: "Royal Challengers Bangalore",
     team_2: "Kolkata Knight Riders",
     Venue: "Holkar Cricket Stadium, Indore",
     wonBy: "Royal Challengers Bangalore",
   },
   {
     year: "2019",
     date: "13-may-2019",
     team_1: "Gujarat Lions",
     team_2: "Delhi Daredevils",
     Venue: "Wankhede Stadium, Mumbai",
     wonBy: "Delhi Daredevils",
   },
   {
     year: "2019",
     date: "14-may-2019",
     team_1: "Rising Pune Supergiants",
     team_2: "Delhi Daredevils",
     Venue: "Eden Gardens, Kolkata",
     wonBy: "Rising Pune Supergiants",
   },
   {
     year: "2019",
     date: "14-may-2019",
     team_1: "Gujarat Lions",
     team_2: "Delhi Daredevils",
     Venue: "Eden Gardens, Kolkata",
     wonBy: "Delhi Daredevils",
   },
   {
     year: "2019",
     date: "15-may-2019",
     team_1: "Gujarat Lions",
     team_2: "Sunrisers Hyderabad",
     Venue: "Rajiv Gandhi Intl. Cricket Stadium, Hyderabad",
     wonBy: "Sunrisers Hyderabad",
   },
   {
     year: "2019",
     date: "16-may-2019",
     team_1: "Mumbai Indians",
     team_2: "Gujarat Lions",
     Venue: "M. Chinnaswamy Stadium, Bengaluru",
     wonBy: "Gujarat Lions",
   },
   {
     year: "2019",
     date: "17-may-2019",
     team_1: "Delhi Daredevils",
     team_2: "Kings XI Punjab",
     Venue: "Rajiv Gandhi Intl. Cricket Stadium, Hyderabad",
     wonBy: "Kings XI Punjab",
   },
   {
     year: "2019",
     date: "18-may-2019",
     team_1: "Gujarat Lions",
     team_2: "Mumbai Indians",
     Venue: "Saurashtra Cricket Association Stadium, Rajkot",
     wonBy: "Gujarat Lions",
   },
   {
     year: "2019",
     date: "19-may-2019",
     team_1: "Sunrisers Hyderabad",
     team_2: "Delhi Daredevils",
     Venue: "Rajiv Gandhi Intl. Cricket Stadium, Hyderabad",
     wonBy: "Delhi Daredevils",
   },
   {
     year: "2019",
     date: "20-may-2019",
     team_1: "Kings XI Punjab",
     team_2: "Delhi Daredevils",
     Venue: "Holkar Cricket Stadium, Indore",
     wonBy: "Delhi Daredevils",
   },
   {
     year: "2019",
     date: "21-may-2019",
     team_1: "Kolkata Knight Riders",
     team_2: "Mumbai Indians",
     Venue: "Eden Gardens, Kolkata",
     wonBy: "Mumbai Indians",
   },
   {
     year: "2019",
     date: "22-may-2019",
     team_1: "Delhi Daredevils",
     team_2: "Mumbai Indians",
     Venue: "Feroz Shah Kotla Ground, Delhi i",
     wonBy: "Delhi Daredevils",
   },
   {
     year: "2019",
     date: "22-may-2019",
     team_1: "Rising Pune Supergiants",
     team_2: "Sunrisers Hyderabad",
     Venue: "Maharashtra Cricket Association's International Stadium, Pune",
     wonBy: "Rising Pune Supergiants",
   },
   {
     year: "2019",
     date: "23-may-2019",
     team_1: "Kings XI Punjab",
     team_2: "Gujarat Lions",
     Venue: "Saurashtra Cricket Association Stadium, Rajkot",
     wonBy: "Gujarat Lions",
   },
   {
     year: "2019",
     date: "23-may-2019",
     team_1: "Kolkata Knight Riders",
     team_2: "Royal Challengers Bangalore",
     Venue: "Eden Gardens, Kolkata",
     wonBy: "Royal Challengers Bangalore",
   },
   {
     year: "2019",
     date: "24-may-2019",
     team_1: "Mumbai Indians",
     team_2: "Rising Pune Supergiants",
     Venue: "Wankhede Stadium, Mumbai",
     wonBy: "Rising Pune Supergiants",
   },
   {
     year: "2019",
     date: "25-may-2019",
     team_1: "Royal Challengers Bangalore",
     team_2: "Sunrisers Hyderabad",
     Venue: "Wankhede Stadium, Mumbai",
     wonBy: "Sunrisers Hyderabad",
   },
   {
     year: "2019",
     date: "26-may-2019",
     team_1: "Rising Pune Supergiants",
     team_2: "Kolkata Knight Riders",
     Venue: "Maharashtra Cricket Association's International Stadium, Pune",
     wonBy: "Kolkata Knight Riders",
   },
   {
     year: "2019",
     date: "27-may-2019",
     team_1: "Delhi Daredevils",
     team_2: "Mumbai Indians",
     Venue: "Maharashtra Cricket Association's International Stadium, Pune",
     wonBy: "Mumbai Indians",
   },
   {
     year: "2019",
     date: "28-may-2019",
     team_1: "Sunrisers Hyderabad",
     team_2: "Delhi Daredevils",
     Venue: "Maharashtra Cricket Association's International Stadium, Pune",
     wonBy: "Delhi Daredevils",
   },
   {
     year: "2019",
     date: "28-may-2019",
     team_1: "Mumbai Indians",
     team_2: "Delhi Daredevils",
     Venue: "Maharashtra Cricket Association's International Stadium, Pune",
     wonBy: "Delhi Daredevils",
   },
  ];
  // function gfg() {
  // arr.match(/Kings XI Punjab/g).length;
  // } 
  return (
    <View style={styles.container}>
      <View style={{
        marginTop: ht *0.04}}>
        <LineChart
          data={{
            labels: ["CSK", "KXIP", "MI", "RR", "SRH", "RCB", "KKR", "DD"],
            datasets: [
              {
                data: [10, 20, 30, 10, 20, 15, 12, 8],
              },
            ],
          }}
          width={Dimensions.get("window").width} // from react-native
          height={ht*0.6}
          chartConfig={{
            backgroundColor: "#e26a00",
            backgroundGradientFrom: "#fb8c00",
            backgroundGradientTo: "#ffa726",
            decimalPlaces: 0, // optional, defaults to 2dp
            color: (opacity = 1) => `rgba(255, 255, 255, ${opacity})`,
            style: {
              borderRadius: 16,
            },
          }}
          bezier
          style={{
            marginVertical: 8,
            borderRadius: 16,
          }}
        />
        <View style={{ flexDirection: "row", justifyContent: "space-around",marginTop: ht *0.04 }}>
          <TouchableOpacity>
            <View style={styles.years}>
              <Text style={styles.yearstext}>2017</Text>
            </View>
          </TouchableOpacity>
          <TouchableOpacity >
            <View style={styles.years}>
              <Text style={styles.yearstext}>2018</Text>
            </View>
          </TouchableOpacity>
          <TouchableOpacity >
            <View style={styles.years}>
              <Text style={styles.yearstext}>2019</Text>
            </View>
          </TouchableOpacity>
        </View>
      </View>
    </View>
  );
}

export default Stats;
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#4D4F79",
    // alignItems: 'center',
    // justifyContent: 'center',
    // marginTop: ht * 0.04,
  },
  years: {
    borderWidth: 1,
    backgroundColor: "black",
    width: wd * 0.30,
    borderColor: "white",
    borderRadius: 50,
  },
  yearstext: {
    color: "white",
    fontWeight: "bold",
    fontSize: ht * 0.05,
    textAlign: "center",
  },
});
